lengow/orders/urls.py
#! /usr/bin/env python3
# coding: utf-8

"""
Author: [Nastyflav](https://github.com/Nastyflav) 2020-19-11
Licence: `GNU GPL v3` GNU GPL v3: http://www.gnu.org/licenses/

"""

from django.urls import path, include
from rest_framework import routers

from orders import views

app_name = 'orders'

router = routers.DefaultRouter()
router.register('orders', views.OrderViewSet)

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('order/<int:pk>', views.OrderDetailsView.as_view(), name='order'),
    path('results/', views.OrderSearchView.as_view(), name='results'),
    path('add/', views.OrderCreateView.as_view(), name='order-add'),
    path(
        'order/update/<int:pk>',
        views.OrderUpdateView.as_view(),
        name='order-update'),
    path('api/', include(router.urls)),
]

lengow/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("orders.urls")),
]

lengow/orders/models.py
#! /usr/bin/env python3
# coding: utf-8

"""
Author: [Nastyflav](https://github.com/Nastyflav) 2020-18-11
Licence: `GNU GPL v3` GNU GPL v3: http://www.gnu.org/licenses/

"""

from django.db import models


class Order(models.Model):
    """Order model, restricted to a few fields"""
    marketplace = models.CharField(
        max_length=100, verbose_name='Marketplace', null=True
    )
    payment_date = models.DateField(
        verbose_name='Date du paiement', null=True
    )
    order_amount = models.DecimalField(
        max_digits=5, decimal_places=2,
        verbose_name='Montant en euros',
        null=True
    )
    currency = models.CharField(
        max_length=5, verbose_name='Devise', null=True
    )

    class Meta:
        verbose_name = 'Commande'

lengow/orders/views.py
#! /usr/bin/env python3
# coding: utf-8

"""
Author: [Nastyflav](https://github.com/Nastyflav) 2020-19-11
Licence: `GNU GPL v3` GNU GPL v3: http://www.gnu.org/licenses/

"""

from django.views.generic import DetailView, ListView, CreateView, UpdateView
from rest_framework. viewsets import ModelViewSet

from orders.models import Order
from orders.serializers import OrderSerializer


class IndexView(ListView):
    """To render the app index with the orders list"""
    template_name = 'orders/index.html'
    model = Order

    def query_set(self):
        return Order.objects.filter().order_by('id')


class OrderDetailsView(DetailView):
    """To render all the fields in every order"""
    model = Order
    template_name = "orders/order_details.html"


class OrderSearchView(ListView):
    """To render the results of the query"""
    model = Order
    template_name = 'orders/query_results.html'

    def get_queryset(self):
        """Get the orders matching with the query"""
        query = self.request.GET.get('query')
        query = str(query).casefold()

        orders = Order.objects.filter(
            marketplace__icontains=query).order_by('id') | \
            Order.objects.filter(
            payment_date__icontains=query).order_by('id') | \
            Order.objects.filter(
            order_amount__icontains=query).order_by('id') | \
            Order.objects.filter(
            currency__icontains=query).order_by('id')

        return orders


class OrderCreateView(CreateView):
    """To create a new order object"""
    model = Order
    fields = ['marketplace', 'payment_date', 'order_amount', 'currency']
    success_url = '/'


class OrderUpdateView(UpdateView):
    """To change any existing order"""
    model = Order
    template_name = 'orders/order_update.html'
    fields = ['marketplace', 'payment_date', 'order_amount', 'currency']
    success_url = '/'


class OrderViewSet(ModelViewSet):
    """To get all the orders and serialize its datas"""
    queryset = Order.objects.all()
    serializer_class = OrderSerializer

lengow/orders/templates/orders/_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Test Lengow</title>
    <!-- CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
</head>
<body>
    <div class="container">
            {% block content %}{% endblock %}
    </div>
</body>
</html>

lengow/orders/templates/orders/index.html
{% extends "orders/_base.html" %}

{% block content %}

<h1>Test Recrutement Lengow</h1>

<div class="row">
    <div class="col-lg-6">
        <h2>Commandes enregistrées</h2>
        {% for order in object_list %}
        <p>
            <a href="{% url 'orders:order' order.id %}">Commande n°{{ order.id }}</a>
        </p>
        {% endfor %}
    </div>
    <div class="col-lg-6">
        <h2>Recherche par champs</h2>
        <form method="get" action="{% url 'orders:results' %}">
            <div>
                <input type="text" name="query" class="form-control" placeholder="Au choix : marketplace / date de paiement / montant / devise" required>
            </div>
            <div>
             <button type="submit">Go!</button>
            </div>
        </form>   
    </div>
</div>

<div class="row">
    <button type="button">
    <a href="{% url 'orders:order-add' %}">Créer une nouvelle commande</a></button>
</div>

{% endblock %}

lengow/orders/templates/orders/order_details.html
{% extends "orders/_base.html" %}

{% block content %}

<h1>Détails de la commande n°{{ object.id }}</h1>

<div class="row">
    <div class="col-lg-10">
        <ul>
            {% if object.marketplace %}
                <li><strong>Marketplace :</strong> {{ object.marketplace }}</li>
            {% else %}
                <li><strong>Marketplace :</strong> Marketplace inconnue</li>
            {% endif %}
            {% if object.payment_date %} 
                <li><strong>Date de paiement :</strong> {{ object.payment_date }}</li>
            {% else %}
                <li><strong>Montant :</strong> Date inconnue </li>
            {% endif %}
            {% if object.order_amount %} 
                <li><strong>Montant :</strong> {{ object.order_amount }}</li>
            {% else %}
                <li><strong>Montant :</strong> Montant inconnu</li>
            {% endif %}
            {% if object.currency %}
                <li><strong>Devise :</strong> {{ object.currency }}</li>
            {% else %}
            <li><strong>Montant :</strong> Devise inconnue</li>
            {% endif %}
        </ul>
        <div class="row">
            <button type="button">
            <a href="{% url 'orders:order-update' object.id %}">Modifier la commande</a></button>
        </div>
    </div>
    <div class="col-lg-2">
        <p>
            <a href="{% url 'orders:index' %}"> Retour à l'accueil</a>
        </p>
    </div>
</div>

{% endblock %}

lengow/orders/templates/orders/order_form.html
{% extends "orders/_base.html" %}

{% block content %}

<h1>Création d'une commande</h1>

<div class="row">
    <div class="col-lg-10">
        <form method="post">{% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Sauvegarder">
        </form>
    </div>
    <div class="col-lg-2">
        <p>
            <a href="{% url 'orders:index' %}"> Retour à l'accueil</a>
        </p>
    </div>
</div>

{% endblock %}

lengow/orders/templates/orders/order_update.html
{% extends "orders/_base.html" %}

{% block content %}

<h1>Modification de la commande n°{{ object.id }}</h1>

<div class="row">
    <div class="col-lg-10">
        <form method="post">{% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Sauvegarder">
        </form>
    </div>
    <div class="col-lg-2">
        <p>
            <a href="{% url 'orders:index' %}"> Retour à l'accueil</a>
        </p>
    </div>
</div>

{% endblock %}

lengow/orders/templates/orders/query_results.html
{% extends "orders/_base.html" %}

{% block content %}

<h1>Résultats de votre recherche</h1>

{% if not object_list %}
<div class="row">
    <div class="col-lg-10">
        <p>Désolé, aucune commande ne correspond à votre recherche</p>
    </div>
    <div class="col-lg-2">
        <p>
            <a href="{% url 'orders:index' %}"> Retour à l'accueil</a>
        </p>
    </div>
</div>

{% else %}

<div class="row">
    <h2>Commandes correspondantes :</h2>
    {% for order in object_list %}
    <div class="col-lg-10">
        <p>
            <a href="{% url 'orders:order' order.id %}">Commande n°{{ order.id }}</a>
        </p>
    </div>
    {% endfor %}
    <div class="col-lg-2">
        <p>
            <a href="{% url 'orders:index' %}"> Retour à l'accueil</a>
        </p>
    </div>
</div>

{% endif %}

{% endblock %}